# Generated by Django 2.2.11 on 2020-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedithistory',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Change description'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Post description'),
        ),
    ]
