# Generated by Django 2.2.11 on 2020-10-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20201026_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
