# Generated by Django 2.2.11 on 2020-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_posts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='location coordinates'),
        ),
    ]
