# Generated by Django 2.2.11 on 2020-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_auto_20201027_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedithistory',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Change description'),
        ),
    ]
